Instanceof redirect and synthetic field shadowing tutorial
2xsaiko/mixin-cheatsheet pull request #7
Opened 2020-11-05 08:40 UTC by BoogieMonster1O1

Credits to @biom4st3r for the instanceof redirect example

2020-11-05 15:44 UTC, 2xsaiko requested changes
Interesting, didn't know you could redirect instanceof.

2020-11-05 15:44 UTC, 2xsaiko commented on shadow-anonymous.md
> +![foo](https://i.imgur.com/hYWE1O3.png)
Could you put these inside the repo?

2020-11-05 15:44 UTC, 2xsaiko commented on redirect.md
> +@Redirect(method = "target()Z", at = @At(value = "CONSTANT",args="classValue=net/example/Dummy",shift=Shift.AFTER,ordinal=0))
Please format the code consistently (spaces before and after "=", spaces after ",", braces on same line, consistent indentation)

2020-11-06 04:42 UTC, BoogieMonster1O1 commented on shadow-anonymous.md
> +![foo](https://i.imgur.com/hYWE1O3.png)
Done, ive put them in `/assets`

2020-11-10 17:56 UTC, merged